GOOSE_MODEL: gemini-2.5-pro-exp-03-25
extensions:
  browser-tools:
    args:
    - '@agentdeskai/browser-tools-mcp@1.1.0'
    cmd: npx
    enabled: true
    name: browser-tools
    type: stdio
  computercontroller:
    enabled: true
    name: computercontroller
    type: builtin
  developer:
    enabled: true
    name: developer
    type: builtin
  fetch:
    args:
    - mcp-server-fetch
    cmd: uvx
    enabled: true
    name: fetch
    type: stdio
  filesystem:
    args:
    - -y
    - '@modelcontextprotocol/server-filesystem'
    - /Users/kevin
    - /Users/kevin/Desktop
    - /Users/kevin/Documents
    - /Users/kevin/Downloads
    - /Users/kevin/sync/projects
    - /Users/kevin/Action
    cmd: npx
    enabled: true
    name: filesystem
    type: stdio
  git:
    args:
    - mcp-server-git
    - --repository
    - /Users/kevin/projects/python/doc_classifier
    cmd: uvx
    enabled: true
    name: git
    type: stdio
  github:
    args:
    - -y
    - '@modelcontextprotocol/server-github'
    cmd: npx
    enabled: true
    envs:
      GITHUB_PERSONAL_ACCESS_TOKEN: ${GITHUB_PERSONAL_ACCESS_TOKEN}
    name: github
    type: stdio
  iterm-mcp:
    args:
    - iterm-mcp
    cmd: npx
    enabled: true
    name: iterm-mcp
    type: stdio
  mcp-installer:
    args:
    - '@anaisbetts/mcp-installer'
    cmd: npx
    enabled: true
    name: mcp-installer
    type: stdio
  memory:
    enabled: true
    name: memory
    type: builtin
  puppeteer:
    args:
    - -y
    - '@modelcontextprotocol/server-puppeteer'
    cmd: npx
    enabled: true
    name: puppeteer
    type: stdio
  reddit:
    args:
    - mcp-server-reddit
    cmd: uvx
    enabled: true
    name: reddit
    type: stdio
  sequential-thinking:
    args:
    - -y
    - '@modelcontextprotocol/server-sequential-thinking'
    cmd: npx
    enabled: true
    name: sequential-thinking
    type: stdio
  tavily:
    args:
    - -y
    - tavily-mcp@0.1.4
    cmd: npx
    enabled: true
    envs:
      TAVILY_API_KEY: ${TAVILY_API_KEY}
    name: tavily
    type: stdio
GOOSE_CLI_MIN_PRIORITY: 0.8
OLLAMA_HOST: localhost
GOOSE_MODE: approve
GOOSE_PROVIDER: google
