GOOSE_MODEL: gemini-2.0-flash-exp
GOOSE_PROVIDER: google
extensions:
  computercontroller:
    enabled: true
    name: computercontroller
    type: builtin
  developer:
    enabled: true
    name: developer
    type: builtin
  github:
    args:
    - -y
    - '@modelcontextprotocol/server-github'
    cmd: npx
    enabled: true
    envs:
      GITHUB_PERSONAL_ACCESS_TOKEN: ${GITHUB_PERSONAL_ACCESS_TOKEN}
    name: github
    type: stdio
  memory:
    enabled: true
    name: memory
    type: builtin
  tavily:
    args:
    - mcp-tavily
    cmd: uvx
    enabled: true
    envs:
      TAVILY_API_KEY: ${TAVILY_API_KEY}
    name: tavily
    type: stdio
GOOSE_MODE: auto
GOOSE_CLI_MIN_PRIORITY: 0.8
