set -g default-terminal "tmux-256color"
set -as terminal-features ",xterm-256color:RGB"
set -g mouse on
set -g history-limit 50000
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on
set -g escape-time 10

bind r source-file ~/.config/tmux/tmux.conf \; display-message "tmux config reloaded"
bind | split-window -h
bind - split-window -v
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

set -g status-interval 5
set -g status-left-length 40
set -g status-right-length 80
set -g status-left "#S "
set -g status-right "#h %Y-%m-%d %H:%M"
