#!/usr/bin/env bash
set -euo pipefail

ROOT="$(git rev-parse --show-toplevel 2>/dev/null)"
MANIFEST="$ROOT/work-wsl/export-manifest.txt"
OVERRIDES="$ROOT/work-wsl/overrides"
DEST=""

usage() {
  cat <<'EOF'
Usage: scripts/export-work-wsl.sh --dest PATH

Build a generated, work-safe WSL mirror from an explicit allowlist.
The destination is treated as disposable: everything except .git is removed
before the mirror is regenerated.
EOF
}

die() {
  printf 'ERR: %s\n' "$*" >&2
  exit 1
}

log() {
  printf '==> %s\n' "$*"
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --dest)
      [[ $# -ge 2 ]] || die "--dest requires a path"
      DEST="$2"
      shift 2
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      die "Unknown argument: $1"
      ;;
  esac
done

[[ -n "$DEST" ]] || die "--dest PATH is required"
[[ -f "$MANIFEST" ]] || die "Missing manifest: $MANIFEST"
[[ -d "$OVERRIDES" ]] || die "Missing overrides directory: $OVERRIDES"

DEST="$(cd "$(dirname "$DEST")" && pwd)/$(basename "$DEST")"
[[ "$DEST" != "$ROOT" ]] || die "Destination cannot be the source repo"
[[ "$DEST" != "$ROOT/"* ]] || die "Destination cannot be inside the source repo"

mkdir -p "$DEST"

log "Clearing generated destination content: $DEST"
find "$DEST" -mindepth 1 -maxdepth 1 ! -name .git -exec rm -rf {} +

copy_tracked_file() {
  local rel="$1"
  local src="$ROOT/$rel"
  local dst="$DEST/$rel"

  git -C "$ROOT" ls-files --error-unmatch -- "$rel" >/dev/null 2>&1 ||
    die "Manifest path is not tracked: $rel"

  mkdir -p "$(dirname "$dst")"
  if [[ -L "$src" ]]; then
    cp -P "$src" "$dst"
  else
    cp -p "$src" "$dst"
  fi
}

log "Copying allowlisted tracked files"
while IFS= read -r line || [[ -n "$line" ]]; do
  line="${line%%#*}"
  line="${line#"${line%%[![:space:]]*}"}"
  line="${line%"${line##*[![:space:]]}"}"
  [[ -n "$line" ]] || continue
  [[ "$line" != /* ]] || die "Manifest paths must be relative: $line"
  [[ "$line" != *".."* ]] || die "Manifest paths may not contain '..': $line"
  copy_tracked_file "$line"
done < "$MANIFEST"

log "Applying work-safe overrides"
while IFS= read -r -d '' src; do
  rel="${src#"$OVERRIDES"/}"
  dst="$DEST/$rel"
  mkdir -p "$(dirname "$dst")"
  cp -p "$src" "$dst"
done < <(find "$OVERRIDES" -type f -print0)

log "Creating generated hook symlinks"
mkdir -p "$DEST/git/git-core.symlink/hooks"
for hook in pre-commit commit-msg prepare-commit-msg post-checkout post-commit post-merge pre-push; do
  ln -snf _dispatcher "$DEST/git/git-core.symlink/hooks/$hook"
done

chmod +x "$DEST/scripts/bootstrap-wsl-work.sh" "$DEST/scripts/audit-wsl-work.sh"
chmod +x "$DEST/git/git-core.symlink/hooks/_dispatcher"

log "Writing generated marker"
mkdir -p "$DEST/.work-wsl"
cat > "$DEST/.work-wsl/generated-by.txt" <<EOF
Generated by scripts/export-work-wsl.sh.
Commit: $(git -C "$ROOT" rev-parse --short HEAD)
EOF

scan_boundary() {
  local matches_file
  matches_file="$(mktemp)"
  trap 'rm -f "$matches_file"' RETURN

  local pattern
  pattern='ntfy|NTFY|ntfy\.sh|claude|codex|gemini|opencode|llm|copilot|kevinmcmahon|/Users/kevin/dotfiles|OPENAI_API_KEY|ANTHROPIC_API_KEY|github_pat_|ghp_|gho_|ghu_|ghs_|ghr_|sk-proj-|sk-'

  if (cd "$DEST" && rg -n --hidden --no-ignore -S "$pattern" . \
      -g '!.git/**' \
      -g '!git/gitconfig-secrets.symlink') \
      >"$matches_file"; then
    cat "$matches_file" >&2
    die "Generated mirror contains blocked personal, AI, notification, or token markers"
  fi

  while IFS= read -r -d '' link; do
    local target
    target="$(readlink "$link")"
    if [[ "$target" = /* ]]; then
      die "Generated symlink uses absolute target: $link -> $target"
    fi
    if [[ "$target" == *".."* ]]; then
      die "Generated symlink escapes its directory: $link -> $target"
    fi
  done < <(find "$DEST" -type l -print0)
}

log "Running safety scan"
scan_boundary

log "Work WSL mirror generated successfully"
